PRIS.Web/Controllers/CourseController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using MoreLinq;
using PRIS.Core.Library.Entities;
using PRIS.Web.Mappings;
using PRIS.Web.Models.CourseModels;
using PRIS.Web.Storage;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PRIS.Web.Controllers
{
    [Microsoft.AspNetCore.Authorization.Authorize]
    public class CourseController : Controller
    {
        private readonly IRepository _repository;
        private readonly ILogger<CourseController> _logger;
        private readonly string _user;

        public CourseController(IRepository repository, ILogger<CourseController> logger, Microsoft.AspNetCore.Http.IHttpContextAccessor httpContextAccessor)
        {
            _repository = repository;
            _logger = logger;
            _user = httpContextAccessor.HttpContext.User.FindFirst(System.Security.Claims.ClaimTypes.Name).Value;
        }
        public async Task<IActionResult> Index(string examId, string courseId, string cityId, string searchString, string sortOrder)
        {
            var students = await _repository.Query<Student>()
                .Include(x => x.ConversationResult)
                .Include(x => x.Result)
                .ThenInclude(x => x.Exam)
                .ThenInclude(x => x.City)
                .Include(x => x.StudentCourses)
                .ThenInclude(x => x.Course)
                .Where(x => x.PassedExam == true)
                .ToListAsync();

            var model = StudentStatisticsData.PrepareData(examId, courseId, cityId, searchString, sortOrder, ref students);

            return View(model);
        }

        public async Task<IActionResult> LockingOfStudentData(string examId, string courseId, string cityId, string searchString, string sortOrder)
        {
            var students = await _repository.Query<Student>()
                .Include(x => x.ConversationResult)
                .Include(x => x.Result)
                .ThenInclude(x => x.Exam)
                .ThenInclude(x => x.City)
                .Include(x => x.StudentCourses)
                .ThenInclude(x => x.Course)
                .Where(x => x.InvitedToStudy == true)
                .ToListAsync();

            var model = StudentLockingData.PrepareData(examId, courseId, cityId, searchString, sortOrder, ref students);

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LockingOfStudentData(int[] studentId, int[] HasSignedAContract, int[] HasStudentDataLocked)
        {
            if (ModelState.IsValid)
            {

                var students = new List<Student>();
                for (int i = 0; i < studentId.Length; i++)
                {
                    students.Add(await _repository.FindByIdAsync<Student>(studentId[i]));
                }
                students.ForEach(x => x.SignedAContract = false);
                for (int i = 0; i < HasSignedAContract.Length; i++)
                {
                    var findStudents = students.FirstOrDefault(x => x.Id == HasSignedAContract[i]);
                    findStudents.SignedAContract = true;
                }
                _logger.LogInformation("{Count} has signed a contract. User {User}",students.Where(x=>x.SignedAContract).Count(), _user);
                var studentsForDataLock = new List<Student>();
                for (int i = 0; i < studentId.Length; i++)
                {
                    studentsForDataLock.Add(await _repository.FindByIdAsync<Student>(studentId[i]));
                }
                var currentUrl = HttpContext.Request.Headers["Referer"];
                studentsForDataLock.ForEach(x => x.StudentDataLocked = false);
                for (int i = 0; i < HasStudentDataLocked.Length; i++)
                {
                    foreach (var student in studentsForDataLock)
                    {
                        if (student.SignedAContract == true)
                        {
                            var findStudents = studentsForDataLock.FirstOrDefault(x => x.Id == HasStudentDataLocked[i]);
                            if (findStudents.SignedAContract == true)
                            {
                                findStudents.StudentDataLocked = true;
                                _logger.LogInformation("Student {Student} data locked. User {User}", student.Id, _user);
                            }
                            else
                            {
                                ModelState.AddModelError("StudentDelete", "Kandidatas turi būti pasirašęs sutartį, kad būtų galima užrakinti kandidato duomenis");
                                TempData["ErrorMessage"] = "Kandidatas turi būti pasirašęs sutartį, kad būtų galima užrakinti kandidato duomenis";
                                _logger.LogWarning("Failed to lock data, the student {Student} must be signed to a contract. User {User}.", student.Id, _user);
                                return Redirect(currentUrl);
                            }
                        }
                    }
                }
                
                await _repository.SaveAsync();
                _logger.LogInformation("Successfully saved data. User {User}.", _user);
                TempData["SuccessMessage"] = "Duomenys sėkmingai išsaugoti";
                
                return Redirect(currentUrl);
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

PRIS.Web/Controllers/ExamsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using PRIS.Core.Library.Entities;
using PRIS.Web.Mappings;
using PRIS.Web.Models;
using PRIS.Web.Storage;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PRIS.Web.Controllers
{
    [Authorize]
    public class ExamsController : Controller
    {
        private readonly IRepository _repository;
        private readonly ILogger<ExamsController> _logger;
        private readonly string _user;

        public ExamsController(IRepository repository, ILogger<ExamsController> logger, Microsoft.AspNetCore.Http.IHttpContextAccessor httpContextAccessor)
        {
            _repository = repository;
            _logger = logger;
            _user = httpContextAccessor.HttpContext.User.FindFirst(System.Security.Claims.ClaimTypes.Name).Value;
        }

        public async Task<IActionResult> Index(int value, [Bind("SelectedCity")] ExamsViewModel viewModel)
        {

            var exams = await _repository.Query<Exam>()
                .Include(exam => exam.City)
                .ToListAsync();
            List<ExamViewModel> examViewModels = new List<ExamViewModel>();
            exams.ForEach(x => examViewModels.Add(ExamMappings.ToViewModel(x)));
            examViewModels = examViewModels.OrderByDescending(x => x.Date).ToList();

            List<string> AcceptancePeriod = await CalculateAcceptancePeriods(examViewModels);

            var AcceptancePeriods = new List<SelectListItem>();
            foreach (var ap in AcceptancePeriod)
            {
                AcceptancePeriods.Add(new SelectListItem { Value = AcceptancePeriod.FindIndex(a => a == ap).ToString(), Text = ap });
            }
            viewModel.AcceptancePeriod = AcceptancePeriods;
            viewModel.ExamViewModels = examViewModels.Where(x => x.SetAcceptancePeriod == AcceptancePeriods.ElementAt(value).Text).ToList();
            var SelectedAcceptancePeriod = AcceptancePeriods.ElementAt(value);
            viewModel.SelectedAcceptancePeriod = SelectedAcceptancePeriod.Text;
            TempData["SelectedAcceptancePeriod"] = SelectedAcceptancePeriod.Value;

            var selectedExams = examViewModels.Where(x => x.SetAcceptancePeriod == SelectedAcceptancePeriod.Text).ToList();

            var results = await _repository.Query<Result>().ToListAsync();
            int studentsCountInAcceptancePeriod = 0;
            foreach (var selectedExam in selectedExams)
            {
                int examId = exams.FirstOrDefault(x => x.Date == selectedExam.Date).Id;
                studentsCountInAcceptancePeriod += results.Count(x => x.ExamId == examId);
            }
            TempData["Count"] = studentsCountInAcceptancePeriod;
            _logger.LogInformation("Found {Count} records. User {User}.", viewModel.ExamViewModels.Count(), _user);
            return View(viewModel);
        }

        public async Task<IActionResult> Create()
        {
            var returnPath = HttpContext.Request.Headers["Referer"].ToString();
            TempData["ReturnPath"] = returnPath;
            ExamViewModel examViewModel = new ExamViewModel();
            List<City> cities = await _repository.Query<City>().ToListAsync();

            var stringCities = new List<SelectListItem>();
            foreach (var city in cities)
            {
                stringCities.Add(new SelectListItem { Value = city.Name, Text = city.Name });
            }
            examViewModel.Cities = stringCities;

            return View(examViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CityId,Date,Comment,Id,Created,SelectedCity")] ExamViewModel examViewModel)
        {
            if (ModelState.IsValid)
            {
                var latestDate = _repository.Query<Exam>()
                                .OrderBy(x => x.Created)
                                .LastOrDefault();
                var exam = ExamMappings.ToEntity(examViewModel);
                var city = await _repository.Query<City>().FirstOrDefaultAsync(x => x.Name == examViewModel.SelectedCity);
                exam.CityId = city.Id;
                var previousUrl = TempData["ReturnPath"].ToString();
                if (latestDate != null)
                {
                    exam.Tasks = latestDate.Tasks;
                    await _repository.InsertAsync(exam);
                    _logger.LogInformation("New exam added to DB. User {User}.", _user);
                    return Redirect(previousUrl);
                }
                else
                {
                    _logger.LogWarning("Exam was null. Nothing added to DB. User {User}.", _user);
                }
                await _repository.InsertAsync(exam);
                return Redirect(previousUrl);
            }
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                _logger.LogWarning("Exam not found. User {User}.", _user);
                return NotFound();
            }

            var exam = await _repository.Query<Exam>()
                .FirstOrDefaultAsync(m => m.Id == id);
            if (exam == null)
            {
                _logger.LogWarning("Can not find exam by provided id. User {User}.", _user);
                return NotFound();
            }
            var examById = await _repository.FindByIdAsync<Exam>(id);
            var result = await _repository.Query<Result>().FirstOrDefaultAsync(x => x.ExamId == examById.Id);
            int.TryParse(TempData["SelectedAcceptancePeriod"].ToString(), out int SelectedAcceptancePeriod);

            if (result != null)
            {
                _logger.LogInformation("Exam has result.");
                var studentById = await _repository.FindByIdAsync<Student>(result.StudentForeignKey);
                if (studentById != null)
                {
                    _logger.LogWarning("Unsuccessful exam delete, exam has one or more students that have passed exam. User {User}.", _user);
                    TempData["ErrorMessage"] = "Testo negalima ištrinti, nes prie jo jau yra priskirta testą išlaikiusių kandidatų.";
                    ModelState.AddModelError("AssignedStudent", "Testo negalima ištrinti, nes prie jo jau yra priskirta testą išlaikiusių kandidatų.");
                }
                else
                {
                    await RemoveFromExams(examById);
                    _logger.LogInformation("Exam {City} {Date} deleted from DB.", examById.City, examById.Date);
                    return Redirect($"/Exams/Index?value={SelectedAcceptancePeriod}");
                }
                return Redirect($"/Exams/Index?value={SelectedAcceptancePeriod}");
            }
            else
            {
                _logger.LogInformation("Exam has no result.");
                var oldestExam = await _repository.Query<Exam>().OrderBy(m => m.Date).FirstOrDefaultAsync();
                await RemoveFromExams(examById);
                _logger.LogInformation("Exam {City} {Date} deleted from DB. User {User}.", examById.City, examById.Date, _user);
                if (examById.Date == oldestExam.Date)
                    return Redirect($"/Exams/Index?value={SelectedAcceptancePeriod - 1}");
                return Redirect($"/Exams/Index?value={SelectedAcceptancePeriod}");
            }
        }

        private async Task<IActionResult> RemoveFromExams(Exam examById)
        {
            await _repository.DeleteAsync<Exam>(examById.Id);
            return RedirectToAction(nameof(Index));
        }

        private async Task<List<string>> CalculateAcceptancePeriods(List<ExamViewModel> examViewModels)
        {
            DateTime firstExamStart = new DateTime(2020, 03, 1);
            DateTime firstExamEnd = new DateTime(2020, 09, 1);
            List<string> AcceptancePeriod = new List<string>();
            foreach (var examViewModel in examViewModels)
            {
                firstExamStart.AddYears(examViewModel.Date.Year - firstExamStart.Year);
                firstExamEnd.AddYears(examViewModel.Date.Year - firstExamEnd.Year);
                var examEntity = await _repository.FindByIdAsync<Exam>(examViewModel.Id);
                if (examViewModel.Date > firstExamStart && examViewModel.Date < firstExamEnd)
                {
                    if (!AcceptancePeriod.Any(x => x == $"{examViewModel.Date.Year} II pusmetis"))
                        AcceptancePeriod.Add($"{examViewModel.Date.Year} II pusmetis");
                    examViewModel.SetAcceptancePeriod = $"{examViewModel.Date.Year} II pusmetis";
                    examEntity.AcceptancePeriod = $"{examViewModel.Date.Year} II pusmetis";
                }
                else
                {
                    if (!AcceptancePeriod.Any(x => x == $"{examViewModel.Date.Year} I pusmetis"))
                        AcceptancePeriod.Add($"{examViewModel.Date.Year} I pusmetis");
                    examViewModel.SetAcceptancePeriod = $"{examViewModel.Date.Year} I pusmetis";
                    examEntity.AcceptancePeriod = $"{examViewModel.Date.Year} I pusmetis";
                }
                await _repository.SaveAsync();
            }
            return AcceptancePeriod;
        }
    }
}

PRIS.Web/Views/Shared/ExamDateList.cshtml
@model IEnumerable<PRIS.Web.Models.ExamViewModel>
@section Slider {

    @foreach (var item in Model)
    {
        <a class="collapse-item" href='@Url.Action("Index", "Students", new { id = item.Id })'>@Html.DisplayFor(modelItem => item.Date)</a>
    }
}

PRIS.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="stylesheet" href="~/lib/fontawesome-free/css/all.min.css" type="text/css" />
    <title>Akademija.it Priėmimo proceso valdymo sistema</title>
    <script src="https://kit.fontawesome.com/6ea83a1e48.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet">
    @*For dataTables*@
    <link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css" rel="stylesheet" />

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
    @*For dataTables*@
</head>

<body id="page-top">

    @if (SignInManager.IsSignedIn(User))
    {

        <!-- Page Wrapper -->
        <div id="wrapper">

            <!-- Sidebar -->
            <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
                <!-- Sidebar - Brand -->
                <a class="sidebar-brand d-flex align-items-center justify-content-center" href='@Url.Action("Main", "Home")'>
                    <div class="sidebar-brand-icon">
                        <img class="logo" src="~/img/it_akademija logo.png" alt="logo" />
                    </div>
                    <div class="sidebar-brand-text pr-3">
                        <div class="logo-name text-right"><img class="img" src="~/img/it_akademija.png" alt="akademija_it_logo" /></div>
                        <sup></sup>
                    </div>
                </a>

                <!-- Divider -->
                <hr class="sidebar-divider my-0">

                <!-- Nav Item - Dashboard -->
                <li class="nav-item">
                    <a class="nav-link" href='@Url.Action("Main", "Home")'>
                        <i class="fas fa-fw fa-tachometer-alt"></i>
                        <span>Pagrindinis puslapis</span>
                    </a>
                </li>

                <!-- Divider -->
                <hr class="sidebar-divider">

                <!-- Heading -->
                @*<div class="sidebar-heading">
                        Interface
                    </div>*@

                <!-- Nav Item - Pages Collapse Menu -->
                <li class="nav-item">
                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
                        <i class="fas fa-city"></i>
                        <span>Miestai ir programos</span>
                    </a>
                    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                        <div class="bg-white py-2 collapse-inner rounded">
                            <h6 class="collapse-header">Miestai ir programos:</h6>
                            <a class="collapse-item" asp-controller="Programs" asp-action="Index">Sąrašas</a>
                            <a class="collapse-item" asp-controller="Programs" asp-action="CreateNewCity">Pridėti miestą</a>
                            <a class="collapse-item" asp-controller="Programs" asp-action="Create">Pridėti programą</a>

                        </div>
                    </div>
                </li>
                <hr class="sidebar-divider">
                <li class="nav-item active">
                    <a class="nav-link" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
                        <i class="fas fa-pencil-alt"></i>
                        <span>Testai</span>
                    </a>
                    <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
                        <div class="bg-white py-2 collapse-inner rounded">
                            <h6 class="collapse-header">Testų sąrašas:</h6>
                            @{
                                //TODO: Testu datu sarasas su foreach
                            }
                            <a class="collapse-item" asp-controller="Exams" asp-action="Index">Testų sąrašas</a>
                            <a class="collapse-item" asp-controller="Exams" asp-action="Create">Sukurti testą</a>
                            <div class="collapse-divider"></div>
                        </div>
                    </div>
                </li>
                <hr class="sidebar-divider">
                <li class="nav-item active">
                    <a class="nav-link" asp-controller="ExamsToConversations" asp-action="Index">
                        <i class="fas fa-fw far fa-comments"></i>
                        <span>Pokalbiai</span>
                    </a>
                </li>
                <hr class="sidebar-divider">
                <li class="nav-item active">
                    <a class="nav-link" href="#" data-toggle="collapse" data-target="#collapsePages2" aria-expanded="true" aria-controls="collapsePages">
                        <i class="fas fa-users"></i>
                        <span>Grupių formavimas</span>
                    </a>
                    <div id="collapsePages2" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
                        <div class="bg-white py-2 collapse-inner rounded">
                            <h6 class="collapse-header">Sąrašas:</h6>
                            <a class="collapse-item" asp-controller="StudentInvitationToStudy" asp-action="Index">Kvietimai studijuoti</a>
                            <a class="collapse-item" asp-controller="Course" asp-action="LockingOfStudentData">Duomenų užrakinimas</a>
                            <div class="collapse-divider"></div>
                        </div>
                    </div>
                </li>
                <hr class="sidebar-divider">
                <li class="nav-item active">
                    <a class="nav-link" asp-controller="Course" asp-action="Index">
                        <i class="fas fa-align-left"></i>
                        <span>Analizė</span>
                    </a>
                </li>
                <!-- Divider -->
                <hr class="sidebar-divider d-none d-md-block">

                <!-- Sidebar Toggler (Sidebar) -->
                <div class="text-center d-none d-md-inline">
                    <button class="rounded-circle border-0" id="sidebarToggle"></button>
                </div>

            </ul>
            <!-- End of Sidebar -->
            <!-- Content Wrapper -->
            <div id="content-wrapper" class="d-flex flex-column">

                <!-- Main Content -->
                <div id="content">

                    <!-- Topbar -->
                    <nav class="navbar navbar-expand navbar-light topbar mb-4 static-top shadow bg-footer-header">

                        <!-- Sidebar Toggle (Topbar) -->
                        <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                            <i class="fa fa-bars"></i>
                        </button>

                        <!-- Topbar Search -->
                        <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                            <h5 class="text-white">Priėmimo proceso valdymo sistema</h5>
                        </form>

                        <!-- Topbar Navbar -->
                        <ul class="navbar-nav ml-auto">

                            <!-- Nav Item - User Information -->
                            <li class="nav-item dropdown no-arrow">
                                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <span class="mr-2 d-none d-lg-inline text-white">@User.Identity.Name</span>
                                    <i class="fa fa-user-circle" style="font-size:40px"></i>
                                </a>
                                <!-- Dropdown - User Information -->
                                <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                                    <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">
                                        <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                        Registracija
                                    </a>
                                    <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Manage/Index">
                                        <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                        Nustatymai
                                    </a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item">
                                        <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                            <i type class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                            <span><button type="submit" class="nav-link btn btn-link buttonWithoutStyle p-0 m-0 h-50">Atsijungti</button></span>
                                        </form>
                                    </a>
                                </div>
                            </li>

                        </ul>

                    </nav>
                    <!-- End of Topbar -->
                    <!-- Begin Page Content -->
                    <div class="container-fluid">
                        <!-- Page Heading -->
                        @RenderBody()
                    </div>
                    <!-- /.container-fluid -->
                </div>
                <!-- End of Main Content -->
                <!-- Footer -->
                <footer class="sticky-footer bg-footer-header">
                    <div class="container my-auto">
                        <div class="copyright text-center my-auto text-white">
                            <span>@DateTime.Now.Year - Bugless &copy;. Visos teisės saugomos.</span>
                        </div>
                    </div>
                </footer>
                <!-- End of Footer -->

            </div>
            <!-- End of Content Wrapper -->

        </div>
        <!-- End of Page Wrapper -->
        <!-- Scroll to Top Button-->
        <a class="scroll-to-top rounded" href="#page-top">
            <i class="fas fa-angle-up"></i>
        </a>

    }
    else
    {
        @RenderBody()
    }
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>

    <script src="~/lib/jquery-easing/jquery.easing.min.js"></script>

    <script src="~/js/sb-admin-2.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>

</html>